### ISSUE TITLE
CreateTikkle 생성시 이미지를 설정 안한 경우 이미지 처리

### ISSUE THREAD

**Issue by three523** [three523/Tikkle#19]
**문제**

Tikkle 생성시 이미지를 안가져 온 경우 기본 이미지를 무엇으로 할지 정하기

**Comment by real-future** [comment]
도현님께서 도와주셔서(이미지 이름을 잘못 입력했었음) 해결완료. 

addphoto와 같을 때 default이미지가 되게끔 로직을 구현하였음.
