### ISSUE TITLE
TikklePage 편집 대신 삭제 기능 구현

### ISSUE THREAD

**Issue by real-future** [three523/Tikkle#28]
**문제**

기획상 TikklePage의 편집 버튼이 없는 게 맞음. 
(마음대로 스탬프 개수를 1개로 줄일 수도 있는 상황이 생길 수 있음)
**해결책**

현재 '편집'버튼 대신 '도전하기/포기하기' 버튼으로 대체

**Comment by three523** [comment]
#50 지훈님이 기능을 구현하셨기 때문에 이슈 닫겠습니다.
