### ISSUE TITLE
'도전하기' 버튼 누르기 전에는 삭제 버튼 보이지 않도록

### ISSUE THREAD

**Issue by real-future** [three523/Tikkle#53]
**문제**

'도전하기' 버튼 누르기 전인데도 삭제버튼이 나옵니다.
아직 내 리스트가 되지 않았는데 삭제 기능이 있어 사용자 입장에서 헷갈릴 수도 있을 것 같습니다.
![simulator_screenshot_757EC6BA-FED0-42DF-8266-4FDDB59537B1](https://github.com/three523/Tikkle/assets/85066307/4793e241-92fe-4998-ad83-47fa687de44e)

**해결책**

'도전하기'버튼 누르기 전에는 삭제버튼이 보이지 않도록 해주세요.

**Comment by three523** [comment]
알겠습니다

**Comment by three523** [comment]
#55 완료
